# Generated by Django 5.1.1 on 2024-11-05 12:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_new_options_new_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'hyzmat',
                'verbose_name_plural': 'hyzmatlar',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 'terminallar',
            },
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
