# Generated by Django 5.1.1 on 2024-11-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_services_terminal_alter_new_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
