# Generated by Django 5.1.1 on 2024-11-07 14:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/', verbose_name='Surat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='image',
            field=models.ImageField(default='', upload_to='terminals/', verbose_name='Surat'),
            preserve_default=False,
        ),
    ]
